### ISSUE TITLE
Add option for shared library

### ISSUE THREAD

**Issue by mdwagner** [amauryt/cr-cmark-gfm#13]
When trying to utilize Crystal's interpreter, it cannot load static libraries, only shared libraries. Adding a recipe in the Makefile for building shared would be a nice option.

**Comment by amauryt** [comment]
My apologies, @mdwagner, for the delay in the response. 

Unfortunately I don't have much bandwidth at the moment, but a PR is more than welcome.

I saw that you opened a [similar issue](https://github.com/kostya/lexbor/issues/39) for the `lexbor` shard, perhaps there is a likewise solution for this shard.
If needed, you can take a look to GitHub's underlying [C library](https://github.com/github/cmark-gfm).

**Comment by amauryt** [comment]
Fixed by PR #14

**Comment by amauryt** [comment]
Fixed in PR #14
